### ISSUE TITLE
scalpel-core (without curl)

### ISSUE THREAD

**Issue by debug-ito** [fimad/scalpel#27]
It would be nice for me if you created something like `scalpel-core` without dependency on `curl` package or functions like `scrapeURL`.

For those who want to use Scalpel purely for scraping (like me), dependency on `curl` is pretty redundant. `curl` depends on libcurl, so users often fail to install it once (and then they install libcurl and try again). This is a little annoying.

**Comment by fimad** [comment]
I like the idea of having a package with lighter dependencies for those that don't need/want curl.

I'm not 100% sure how that work logistically. Ideally I'd like to only have a single version of the documentation but also I think I would probably want the main documentation to be visible in the haddock of both packages.

Do you have any recommendations for how this would work in practice?

An alternative, (if the real problem is curl and dependencies on non-Haskell libraries) is that we could swap out the curl dependency for something like [wreq](https://hackage.haskell.org/package/wreq).

**Comment by debug-ito** [comment]
By "main documentation" you mean the one at the top of `Text.HTML.Scalpel` module? If so, I think it's tricky to make it visible from both packages. I'm not sure how to do that.

However, I don't need that personally. We already have `scalpel` package, so the main documentation stays in it. I would add document (near `scrapeURL` and to the description of scalpel.cabal) that mentions `scalpel-core` for those who don't want network support. In the document of `scalpel-core`, I would just put a pointer to `scalpel` for usage documentation.

As for the alternative approach, that would be a backward-incompatible change, because scalpel already exposes types from curl (e.g. `CurlOption`). Plus, I think wreq is still too heavy. [http-client](https://hackage.haskell.org/package/http-client) and [http-client-tls](https://hackage.haskell.org/package/http-client-tls) are sufficient.

**Comment by 3noch** [comment]
I definitely agree @debug-ito has a good idea of pulling the logic out into `scalpel-core` and leaving the API interface for `scalpel` the same. I too don't want to pull in curl.

**Comment by 3noch** [comment]
In my case I'd like to build out a tor-based backend for scraping.

**Comment by fimad** [comment]
Published version 0.5.0 which these changes.

**Comment by 3noch** [comment]
Thank you!

**Comment by debug-ito** [comment]
Thanks a lot!

**Comment by fimad** [comment]
No problem :)
