### ISSUE TITLE
Getting nth element?

### ISSUE THREAD

**Issue by aupiff** [fimad/scalpel#38]
If I'm working with html resembling the following,

```html
<table>
  <tr>
    <td><strong>col 1</strong></td>
    <td><a href="special-link">col 2</a></td>
    <td>col k</td>
  </tr>
  <tr>
    <td>col 1</td>
    <td><a href="special-link">col 2</a></td>
    <td>col k</td>
  </tr>
  <tr>
    <td><a href="link">col 1</a></td>
    <td><a href="special-link">col 2</td>
    <td>col k</td>
  </tr>
</table>		
```

What is the suggested way to use Scalpel to extract the `n`th `td` from each `tr`? Notice that we can only be sure of the form of the column of interest, and that the other `td`s in each row have variable structure.

I'm resorting to hacky solutions that look like:

```Haskell
tableScraper :: Scraper String [String]
tableScraper = chroot ("table" :: String) $
    chroots ("tr" :: String) $ (!! 1) <$> columnLinkScraper

columnLinkScraper = chroots ("td" :: String) $
    attr ("href" :: String) ("a" :: String) <|> return ""

main :: IO ()
main = hspec $ do

  describe "scalpel" $
    it "parsed well" $ do
        contents <- readFile "test.html"
        let scrapedLinks = scrapeStringLike contents tableScraper
        case scrapedLinks of
           Just links -> links `shouldBe` replicate (length links) "special-link"
           Nothing -> scrapedLinks `shouldSatisfy` isJust
```

Is there a better way to do this? Does a `chrootIndex :: Int -> s -> Scraper str a -> Scraper str a` function make sense? `chroot` is essentially just `chrootHead`, after all. I've looked at the implementation of `chroot` and is seems like we would just need to use an alternative `chroots` that doesn't use the `mapMaybe` function and preserves the total number of matched root tags. I'm happy to write this function if everyone thinks it's a good idea.

**Comment by aupiff** [comment]
Ughh... I'll reopen this if I come up with a more thoughtful suggestion.

**Comment by fimad** [comment]
I spent a while trying to come up with a non-hacky way of doing this with the currently exposed methods and couldn't figure anything out.

It seems like your problem is a specific case of generally not having access to the context of the current element. For example, what if we added a function `position :: Scaper str Int` that returns the current index. You could solve your problem by doing:

```haskell
tableScraper :: Scraper String [String]
tableScrape = chroots "tr" $ chroot "td" $ do
    p <- position
    guard $ p == 1
    attr "href" "a"
```

You could also use it to perform more complex constraints on the index that would be more difficult with chrootIndex, like grabbing every other element:

```haskell
evenLinks :: Scraper String [[String]]
evenLinks = chroots "tr" $ chroots "td" $ do
    p <- position
    guard $ (p % 2) == 0
    attr "href" "a"
```

**Comment by aupiff** [comment]
Oh, I really like your `position` suggestion. I'll work on a solution over the next few days.

**Comment by aupiff** [comment]
Hey all,

Within a `chroots` funciton, the `inner` scraper has access to only the elements within the matching tags. For example,

```Haskell
chroots "a" $ inner
```

when scraping something like

``` Haskell
scrape (\"<a>1</a><a>2</a><a>3</a>\")"
```

Will see the following `TagSpec`s within `chroots`.

```Haskell
TagSpec: ([TagInfo {infoTag = TagOpen "a" [], infoName = Just "a", infoIndex = 0, infoOffset = Just 2},TagInfo {infoTag = TagText "1", infoName = Nothing, infoIndex = 1, infoOffset = Nothing},TagInfo {infoTag = TagClose "a", infoName = Just "a", infoIndex = 2, infoOffset = Nothing}],[Node {rootLabel = Span 0 2, subForest = []}])

TagSpec: ([TagInfo {infoTag = TagOpen "a" [], infoName = Just "a", infoIndex = 3, infoOffset = Just 2},TagInfo {infoTag = TagText "2", infoName = Nothing, infoIndex = 4, infoOffset = Nothing},TagInfo {infoTag = TagClose "a", infoName = Just "a", infoIndex = 5, infoOffset = Nothing}],[Node {rootLabel = Span 0 2, subForest = []}])

TagSpec: ([TagInfo {infoTag = TagOpen "a" [], infoName = Just "a", infoIndex = 6, infoOffset = Just 2},TagInfo {infoTag = TagText "3", infoName = Nothing, infoIndex = 7, infoOffset = Nothing},TagInfo {infoTag = TagClose "a", infoName = Just "a", infoIndex = 8, infoOffset = Nothing}],[Node {rootLabel = Span 0 2, subForest = []}])
```

My first thought would be to move to a zipper representation of the HTML tree. Then each scraper could access information about the global structure or the document. `chroot` would become a trivial re-focusing of the zipper.

This might take me a while to implement and I think a lot of the code would have to change (key functions like `select`, `selectNodes`), so let me know if you think this is too vast a change or have other suggestions.

**Comment by cyrbon** [comment]
In my experience, getting n-th element is a very frequent usecase when parsing pages. Having `position` would be amazing and make it a lot cleaner.

For the record, I've tried implementing it myself. But it's my first time using TagSoup and I've been only using Scalpel and TagSoup for a couple of hours, so I wasn't able to find a trivial implementation and had to give up. My first guess was checking out TagSoup' `TagPosition Row Column` and Scalpel's `TagSpec` with `infoIndex :: Int` and `infoOffset :: Maybe Int`, but, when I was playing around  with source (using `attr` and `tagsToAttr` functions as a blueprint), neither of them seem to be related to this and it quickly became obvious that it might require a lot of code change rather than a simple hack.

**Comment by aupiff** [comment]
I am thinking that a position predicate should be passed to a `chroots`-like function instead of accessing it within the "inner scraper" of `chroots`. This would avoid the need to change data structures and would make this a quick fix.

I've said this before, but this week I really do think that I'll have time to make this change!

**Comment by fimad** [comment]
I am hesitant about adding a predicate to `chroots` since its not very future friendly. If we decide that we'd like to be able to condition on some additional piece of metadata then it would be cumbersome to try to add that.

I think the least intrusive way to add `position` would be to update `TagSpec` to include a type for ephemeral metadata. We could put the current match index (I'm also wondering if `position` is too generic a name and that maybe something like `matchIndex` or `matchOrder` wouldn't be more appropriate) in there now and it would also provide a place to shove future metadata that may change between select invocations.

I think the easiest way to figure out the position would be in `select` to zip the result of `selectNodes` with `[0..]` and store that in the new TagSpec piece.

**Comment by cyrbon** [comment]
@fimad  Great commit!

**Comment by fimad** [comment]
No problem :)
