### ISSUE TITLE
Generalize singular and plural scrapers

### ISSUE THREAD

**Issue by 3noch** [fimad/scalpel#56]
Having singular and plural versions of all top-level scraper functions seems like a poor API. A singular scraper could easily be built from a plural scraper by simply selecting the first one. Getting optimal performance might be a little tricky but certainly not impossible. Have you considered this?

**Comment by fimad** [comment]
Its not something I've given a lot of thought to, but I'd be open for suggestions if you have any.

I don't think performance would be much of a concern, at least with the current implementation (e.g. `chroot` is already implemented in terms of `chroots`).

What I would be most concerned about would be keeping the API usable in common use cases and I think wanting the first match (and backtracking if there isn't one) is common enough that the API should optimize for it.

While its possible to go from any of the plural APIs to the singular version I'm not aware of concise way to do so that causes backtracking when the list is empty. For example `chroot` is current implemented as the following way which seems overly complicated for users to write every time they just want the head of a list:

```haskell
chroot selector inner = do
    maybeResult <- listToMaybe <$> chroots selector inner
    guard (isJust maybeResult)
    return $ fromJust maybeResult
```

There's also some precedent in other parsing libraries for providing specialized functions that could be implemented in terms of other more general methods, for example [many1](https://hackage.haskell.org/package/parsec-3.1.11/docs/Text-Parsec-Combinator.html#v:many1) in parsec.

**Comment by 3noch** [comment]
Thanks for the detailed response. Could you explain how backtracking comes into play? If you always select the first find, when would you backtrack?

**Comment by fimad** [comment]
It comes into play when you have a nested scrapers. For example consider nesting a text inside a chroot (`chroot "a" (text "b")`). If the first encountered `a` tag does not contain a `b`, then scalpel will backtrack and try the next `a`.

```haskell
ghci> scrapeStringLike "<a></a><a><b>foo</b></a>" $ chroot "a" (text "b")
Just "foo"
```

However, if you nest a texts inside a chroot (`chroot "a" (texts "b")`) the texts scraper will not fail if there are no `b` tags. Instead it will return an empty list:

```haskell
ghci> scrapeStringLike "<a></a><a><b>foo</b></a>" $ chroot "a" (texts "b")
Just []
```

If you wanted to replicate the behavior of `text` while using `texts` you would have to make the scraper fail in the case of an empty list. Which would look something like:

```haskell
ghci> scrapeStringLike "<a></a><a><b>foo</b></a>" $ chroot "a" (texts "b" >>= ((>>) <$> guard . not . null <*> return . head))
Just "foo"
```

**Comment by 3noch** [comment]
Fair enough. In this case the singular and plural versions are different enough that I agree they deserve separate APIs. It does seem to be subtle, though, but I'm guessing that in the context of a Scraper this behavior is intuitive.
