### ISSUE TITLE
Select nth element?

### ISSUE THREAD

**Issue by farao** [fimad/scalpel#63]
Hi,

in scalpel there some functions that simply return the "first match" - e.g. text or chroot. Is there a way to select/chroot the nth matching element? Suppose, I have the following HTML:
<div>
<p>One</p>
<p>Two</p>
</div>
Now I want to select only the second <p> - is there a way to do this?

Thanks,
Marius

**Comment by fimad** [comment]
I would recommend `fmap`ing `drop` over the all of the matches, and then pattern matching to pull out the first element:

```haskell
scrapeStringLike "<div><p>One</p><p>Two</p></div>" $ do 
  a:_ <- drop 1 <$> texts "p"
  return a
```

Failing a pattern match inside the Scraper monad is safe because it is an instance of [MonadFail](https://hackage.haskell.org/package/base-4.10.1.0/docs/Control-Monad-Fail.html).
