### ISSUE TITLE
Replace Maybe with a descriptive error type (Either)

### ISSUE THREAD

**Issue by KaneTW** [fimad/scalpel#98]
When parsing fails for whatever reason, scrape always returns a Maybe due to the MaybeT transformer. This loses any error information for why parsing actually failed.

I propose replacing MaybeT with ExceptT.

**Comment by fimad** [comment]
That would require a breaking API change, which is doable but I want to make sure we have all the aspects of it thought through:

- Is the error type specified by the user? Something scalpel provided?
- How much effort and what is required to migrate existing code?

**Comment by KaneTW** [comment]
I started working on it locally, but it seems complicated. Would need some architectural changes I don't have the overview for.

The way Parsec reports errors seems pretty appropriate, but I'd have to look up how exactly it works under the hood

**Comment by benjaminweb** [comment]
Chiming in here, @KaneTW.
Context: Scraping product from product page.
Two outcomes:
a. We can scrape a `Product` from the page.
b. Or we cannot (because the page has changed and our scraper no longer work).

We want to know once the page has changed so we can adopt our scraper accordingly!

Approach. We collect everything for a `Product` but don’t construct it within the scraper.
That way we can let return the scraper always something. Let’s call it `ProductDto`.
This `ProductDto` carries only `Maybe` values.

Now, in case our scraper fails to even return a `Just ProductDto`, it will return a `Nothing`.
Getting that, we could translate it to a null `ProductDto`, holding only values of `Nothing`.
That’d be a wrapper around our scraper.

So, now that we always get a `ProductDto`, we always have a construction kit for constructing a `Product`.
If the `ProductDto` is valid as to we can construct a `Product `from it, we do just that.
If values are invalid or we don’t have everything to construct a `Product`, we translate the specific condition to something like `ScrapeError` with variants explaining what the condition is. If we have multiple conditions, we might return multiple conditions to be comprehensive here.

Now, the function’s signature could look like:
```haskell
createProduct :: ProductDto -> Either Product [ScrapeError]
```

@fimad what’s your take on this?

**Comment by benjaminweb** [comment]
I've defined `ScraperT str (Except e) a` and try to implement `textComment'''`.
`textComment'''` should do a `throwError "some sensible message" when the selector cannot find the specified target.
How can I check whether `author <- text authorSel` was not successful?
https://github.com/benjaminweb/scalpel-exceptt/blob/main/src/Lib.hs#L136-L141

**Comment by fimad** [comment]
Given that this doesn't require a ton of additional code on the users behalf, I plan to update the documentation with some of these examples but not change the API to add types like `ScraperWithError`.

I think it makes sense to keep the API simple and unopinionated about error handling and then the user can choose the types and approach that makes sense for them / works well with their code base.
